### PR TITLE
Use SITL JSON Interface 

### PR DESCRIPTION
**Pull request by srmainwaring**
This PR changes the ArduPilotGazebo plugin to use the SITL JSON interface.

The purpose of the this PR is to change the ArduPilotGazebo plugin to use the new SITL JSON interface. This replaces the current binary contract for data return to SITL with a JSON schema based contract (data received from SITL is still binary).
This should aid in supporting new sensor inputs to SITL from Gazebo as it will no longer be necessary to coordinate the simultaneous release of the plugin and ArduPilot.

Further, it permits SITL to optionally consume sensor data from Gazebo if it is provided, or default to SITL provided sensor data when it is not.

This PR is currently WIP for review and testing.

- the bidirectional link to SITL is operational but subject to connection timeouts which must be addressed
- there is no testing of the received data for the correct protocol byte, frame rates and frame ordering
- the use of the SocketAPM class may or may not be permitted subject to licensing
- there is a new dependency on the jsoncpp library which needs to be reviewed

### CODE REVIEW

**Comment by srmainwaring** [comment]
Instrumenting the plugin revealed jsoncpp to incur unreasonable overhead when sending the state. [Native JSON Benchmark](https://github.com/miloyip/nativejson-benchmark#stringify-time) suggests [RapidJSON](https://github.com/Tencent/rapidjson) might be a better alternative and tests with examples and plugins bear this out.

With RapidJSON performance with Gazebo + SITL-JSON is still not as good as Gazebo + SITL-Gazebo but it is improved (a sim that ran RTF~97 with the binary protocol is running RTF~85-95: the new interface has has a larger variation in the RTF).

**Comment by srmainwaring** [comment]
The optional servo limits are required when the SITL supplied PWM values are outside the range [1000, 2000].

An example of when this occurs is the Quadruped model [GSoC 2020: Walking Robot Support For Ardupilot](https://discuss.ardupilot.org/t/gsoc-2020-walking-robot-support-for-ardupilot/57080). The Lua script for this model outputs servo PWM values in the range [500, 2500]. Without an option to rescale the controller commands with bounds the output joint positions will not be correct (and cannot be fixed by simply rescaling with a multiplier and offset).

**Comment by zdanek** [comment]
Hello. Will this PR allow using Gazebo-11? 
I run Gazebo-11 and it's not compatible w Ardupilit SITL. It gets FDM frame errors and does not comunicate. I suppose using json might be a solution.

**Comment by zdanek** [comment]
@srmainwaring  regarding
> Reducing the socket.recv timeout to 10ms resolves most of the performance issue, because if `ReceiveMotorCommand()` blocks then the main Gazebo world update is also blocked.
> 
> The plugin continues to check that there are no more than `connectionTimeoutMaxCount` misses and will go offline if this occurs.

I suggest using a dedicated thread for receiving data. See
https://github.com/mavlink/c_uart_interface_example
there's a separate thread to receive mavlink messages through UDP. 

> 
> _Question: what are the consequences of the plugin sending data to SITL multiple times for the same frame?_
If you'd use separate thread for receiving frames you can also set receive time and control whether to push the data to Gazebo or skip it if it's not expected to push more data than one per frame.

Should you have any thoughts on mine please post them here.

**Comment by srmainwaring** [comment]
@zdanek 

> Will this PR allow using Gazebo-11

It runs with Gazebo11 on macOS 10.15.7 (Gazebo and ignition dependencies built from source rather than from the osrf/simulation tap). I have not tested on Ubunutu, but can look into that, although this PR is not specifically targeting any specific Gazebo 11 compatibility issues.

> I suggest using a dedicated thread for receiving data

That might be worth looking into if I continue to see issues. The current configuration is working well on the localhost interface at least.

The outgoing data is timestamped and SITL adjusts its timing to lockstep with the messages returned from Gazebo.

**Comment by srmainwaring** [comment]
Building on Ubtuntu 18.04 revealed that the cmake find_package argument for RapidJSON package is case sensitive. Also add a note for installing gazebo11 on Ubuntu as some of the examples require a later version of sdf.

**Comment by not7cd** [comment]
@srmainwaring, how stable is this PR. Is it worth pursuing, or should I start looking into https://github.com/ArduPilot/ardupilot_gazebo?

**Comment by srmainwaring** [comment]
@not7cd, thanks for the reminder - I should close this as the focus has shifted to the latest generation of Gazebo.

If you plan to use Gazebo Garden then ArduPilot/ardupilot_gazebo is the version you want.

**Pull request closed without merging**
