### PR TITLE
add uninstall target for cmake

### LINKED ISSUE #32: [Feature Request] make `uninstall` target
It would be nice if a `make uninstall` target is provided via CMake, so that users can uninstall the codebase easily.

### PR DESCRIPTION
**Pull request by acxz**
resolves #32

### CODE REVIEW

**Comment by acxz** [comment]
@khancyr can you take a look at this PR? Thanks

**Comment by acxz** [comment]
@khancyr would appreciate if you can provide closure to this PR.

**Comment by acxz** [comment]
@khancyr it has been a month, can you provide feedback on this PR?

**Comment by khancyr** [comment]
it just miss to remove the directories
```
/models/iris_with_ardupilot
/models/iris_with_standoffs
/models/iris_with_standoffs/meshes
```
but I guess it is good enough, thanks !

**Pull request merged**
